# Generated by Django 5.0 on 2024-02-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cuver',
            field=models.ImageField(null=True, upload_to='cuver_picture'),
        ),
        migrations.AlterField(
            model_name='post',
            name='no_likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
