# Generated by Django 5.0 on 2024-02-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cuver',
            field=models.ImageField(default='download (1).jfif', null=True, upload_to='cuver_picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_picture'),
        ),
    ]
